name: ecommerce_pojo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter :
  dio :
  bloc : ^9.0.0
  flutter_bloc : ^9.1.0
  google_sign_in : ^6.2.2
  easy_localization :
  flutter_screenutil :
  google_fonts :
  fluttertoast : ^8.2.12
  loader_overlay :
  animate_do :
  animated_toggle_switch :
  cached_network_image :
  #connectivity_plus :
  carousel_slider:
  flutter_svg:
  shared_preferences :
  get_it:
  flutter_native_splash:
  readmore:
  smooth_page_indicator:  
  dartz: ^0.10.1
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  freezed: ^2.5.7
  equatable: ^2.0.7
  flutter_gen:
  redacted: ^1.0.13
  go_router:
  internet_connection_checker_plus: ^2.7.0

flutter_gen:
  output: lib/core/utils/
  assets:
    enabled: true 
    exclude:
      - assets/translations/

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logos/app_logo_splash_light.png"
  color_dark: "#1E1E1E"
  image_dark: "assets/logos/app_logo_splash_dark.png"

  android_12:
    image: "assets/logos/app_logo_splash_light.png"
    image_dark: "assets/logos/app_logo_splash_dark.png"
    color_dark: "#1E1E1E"
    color: "#ffffff"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  injectable_generator:
  flutter_gen_runner: 

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/translations/
